sudo: false
language: go
go:
- 1.11 # Latest GAE standard
env:
  global:
  - GAE_SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.48.zip
  - PATH=$HOME/go_appengine:$PATH
cache:
  directories:
  - "$HOME/go_appengine"

install:
- "[ -f $HOME/go_appengine/goapp ] || (curl -sSLo $HOME/sdk.zip $GAE_SDK_URL && unzip -q -d $HOME $HOME/sdk.zip)"
- goapp get -d google.golang.org/appengine
- goapp get -d ./...

script:
- goapp test -v ./...
- go vet ./...
- "go get golang.org/x/lint/golint && golint ./..."
